FROM golang:1.19-alpine AS build-stage

RUN apk update && apk add ca-certificates

WORKDIR /app
COPY . ./

WORKDIR /app/services/default/{{.ServiceName}}
RUN go mod download

WORKDIR /app/libs/go/persistence/
RUN go mod download

WORKDIR /app
RUN CGO_ENABLED=0 \
  go build \
  -ldflags="-s -w" \
  -o /app/bin/service \
  /app/services/default/{{.ServiceName}}/cmd/main.go

FROM scratch
COPY --from=build-stage /app/bin/service ./service
COPY --from=build-stage /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
CMD ["./service"]
