GITHUB_SHA?=${shell git rev-parse --short HEAD || echo latest}

DOCKER_IMAGE_BASE = {{.ProjectName}}.{{.ServiceNamespace}}.{{.ServiceName}}
# Assuming the local Docker registry to be the kind-registry container created by create_local_cluster.sh
DOCKER_LOCAL_REGISTRY = 127.0.0.1:8081
# The DOCKER_LOCAL_IMAGE_NAME_TAG has the following format: [REGISTRY]/[PROJECT/NAMESPACE]/[SERVICE]:[TAG]
DOCKER_LOCAL_IMAGE_NAME_TAG = $(DOCKER_LOCAL_REGISTRY)/$(DOCKER_IMAGE_BASE):latest

test:
	@go test -race -coverprofile=coverage.txt -v $$(go list ./...)
.PHONY: test

run:
	@go run cmd/main.go
.PHONY: run

# !!! IMPORTANT !!! The Docker build context is set to the project root directory
# by specifying it using the relative path: ./../../..
build-image:
	@echo "Building *LOCAL* Docker image with name and tag: [{{.Registry}}/${DOCKER_IMAGE_BASE}:latest]"
	@echo "-----------------------------------------------"
	docker build \
		--file ./Dockerfile \
		--progress=plain \
		--tag "{{.Registry}}/${DOCKER_IMAGE_BASE}:${GITHUB_SHA}" \
		--tag "{{.Registry}}/${DOCKER_IMAGE_BASE}:latest" \
		./../../..
.PHONY: build-image

push-image: build-image
	@echo "Pushing *LOCAL* Docker image with name and tag: [{{.Registry}}/${DOCKER_IMAGE_BASE}:latest]"
	@echo "-----------------------------------------------"
	docker push "{{.Registry}}/${DOCKER_IMAGE_BASE}:${GITHUB_SHA}"
	docker push "{{.Registry}}/${DOCKER_IMAGE_BASE}:latest"
.PHONY: push-image

deploy: push-image
	@kubectl apply -f manifests.yml
.PHONY: deploy


# !!! IMPORTANT !!! The Docker build context is set to the project root directory
# by specifying it using the relative path: ./../../..
build-image-local:
	@echo "Building *LOCAL* Docker image with name and tag: [$(DOCKER_LOCAL_IMAGE_NAME_TAG)]"
	@echo "-----------------------------------------------"
	docker build \
		--file ./Dockerfile \
		--progress=plain \
		--tag "$(DOCKER_LOCAL_IMAGE_NAME_TAG)" \
		./../../..
.PHONY: build-image-local

push-image-local: build-image-local
	@echo "Pushing *LOCAL* Docker image with name and tag: [$(DOCKER_LOCAL_IMAGE_NAME_TAG)]"
	@echo "-----------------------------------------------"
	docker push "$(DOCKER_LOCAL_IMAGE_NAME_TAG)"
.PHONY: push-image-local

deploy-local: push-image-local
	yq '(select(.kind == "Deployment") | .spec.template.spec.containers[0].image) = \
		"$(DOCKER_LOCAL_IMAGE_NAME_TAG)"' manifests.yml | kubectl apply -f -
.PHONY: deploy-local

port-forward-local:
	kubectl port-forward -n {{.ServiceNamespace}} service/{{.ServiceName}}-svc 8080:8080
.PHONY: port-forward-local
